In [9]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Using cached pandas-2.3.3-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.8 MB)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/casa/.local/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Collecting numpy>=1.22.4
  Using cached numpy-2.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Collecting tzdata>=2022.7
  Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: tzdata, numpy, pandas
ERROR: Operation cancelled by user
^C
Note: you may need to restart the kernel to use updated packages.

Import Librerias

In [15]:
import requests 
import json
from pandas import json_normalize
import pandas as pd
import random
import string

CODE call API

In [30]:
respuesta=requests.get('https://api.agify.io/?name='+nombre)
print(respuesta)
data=respuesta.json()
data
df=json_normalize(data)
df

<Response [429]>

                   error
0  Request limit reached

In [27]:
df

        count      name   age                  error
0    179232.0      luis    63                    NaN
1         0.0  {nombre}  None                    NaN
2         0.0  {nombre}  None                    NaN
3         0.0  {nombre}  None                    NaN
4         0.0  {nombre}  None                    NaN
..        ...       ...   ...                    ...
199       NaN       NaN   NaN  Request limit reached
200       NaN       NaN   NaN  Request limit reached
201       NaN       NaN   NaN  Request limit reached
202       NaN       NaN   NaN  Request limit reached
203       NaN       NaN   NaN  Request limit reached

[204 rows x 4 columns]

In [29]:
data['age']
df=json_normalize(data)
df

KeyError: 'age'