In [24]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.9/250.9 KB 2.1 MB/s eta 0:00:00[36m0:00:01m eta 0:00:01
Collecting et-xmlfile
  Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [25]:

import pandas as pd

In [26]:
#/home/casa/Escritorio/DESKTOP ALFREDO/Learning PAth/Python
 
dataframe = pd.read_excel('Ejemplo_excel.xlsx')

dataframe

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [32]:
dataframe['e']=[20,30,40,50]
dataframe

   Unnamed: 0   a   b   c   d   e
0           0   0   1   2   3  20
1           1   4   5   6   7  30
2           2   8   9  10  11  40
3           3  12  13  14  15  50

In [33]:
dataframe.to_excel('salida_excel.xlsx', sheetname)