In [1]:
import pandas as pd #Se usa para manejo de datos.
import numpy as np #Se encarga de las operaciones matemáticas
import matplotlib.pyplot as plt # Es la librería base para crear gráficos
import seaborn as sns #Es una capa extra sobre matplotlib para hacer gráficos estadísticos bonitos.

In [4]:
vinos =pd.read_csv("vino.csv")
vinos

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,Wine Type
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,One
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,One
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,One
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,One
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,One
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,Three
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,Three
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,Three
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,Three
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,Three

In [5]:
pwd

'/home/casa'

In [7]:
vinos.columns

Index(['Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium',
       'Total phenols', 'Flavanoids', 'Nonflavanoid phenols',
       'Proanthocyanins', 'Color intensity', 'Hue',
       'OD280/OD315 of diluted wines', 'Proline', 'Wine Type'],
      dtype='object')

In [8]:
vinos['Wine Type'].unique()

array(['One', 'Two', 'Three'], dtype=object)

In [13]:
vinos['Wine Type'].value_counts()

Wine Type
Two      71
One      59
Three    48
Name: count, dtype: int64

In [18]:
X=vinos.drop('Wine Type', axis =1)
X

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [20]:
y=vinos['Wine Type']
y

0        One
1        One
2        One
3        One
4        One
       ...
173    Three
174    Three
175    Three
176    Three
177    Three
Name: Wine Type, Length: 178, dtype: object

In [22]:
from sklearn.model_selection import train_test_split
#para entrenar

In [24]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.3 )

In [25]:
X_train

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
32,13.68,1.83,2.36,17.2,104.0,2.42,2.69,0.42,1.97,3.84,1.23,2.87,990.0
121,11.56,2.05,3.23,28.5,119.0,3.18,5.08,0.47,1.87,6.00,0.93,3.69,465.0
162,12.85,3.27,2.58,22.0,106.0,1.65,0.60,0.60,0.96,5.58,0.87,2.11,570.0
45,14.21,4.04,2.44,18.9,111.0,2.85,2.65,0.30,1.25,5.24,0.87,3.33,1080.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,12.82,3.37,2.30,19.5,88.0,1.48,0.66,0.40,0.97,10.26,0.72,1.75,685.0
7,14.06,2.15,2.61,17.6,121.0,2.60,2.51,0.31,1.25,5.05,1.06,3.58,1295.0
150,13.50,3.12,2.62,24.0,123.0,1.40,1.57,0.22,1.25,8.60,0.59,1.30,500.0
136,12.25,4.72,2.54,21.0,89.0,1.38,0.47,0.53,0.80,3.85,0.75,1.27,720.0
82,12.08,1.13,2.51,24.0,78.0,2.00,1.58,0.40,1.40,2.20,1.31,2.72,630.0

In [27]:
from sklearn.tree import DecisionTreeClassifier #modelo de arbol de desicion

In [29]:
arbol =DecisionTreeClassifier()
arbol.fit(X_train, y_train)

DecisionTreeClassifier()

In [32]:
predicciones=arbol.predict(X_test)
predicciones

array(['One', 'Two', 'Two', 'Two', 'Two', 'One', 'Two', 'Two', 'Three',
       'One', 'One', 'Two', 'Three', 'One', 'Two', 'One', 'Two', 'One',
       'One', 'Two', 'Three', 'Three', 'One', 'Two', 'Two', 'One', 'One',
       'Two', 'One', 'Two', 'Two', 'One', 'Three', 'One', 'Two', 'Two',
       'One', 'One', 'Three', 'Two', 'Three', 'Three', 'Three', 'Three',
       'Two', 'Two', 'One', 'Two', 'Three', 'Two', 'Two', 'Three',
       'Three', 'Three'], dtype=object)

In [33]:
y_test

26       One
119      Two
73       Two
103      Two
114      Two
16       One
64       Two
24       One
165    Three
9        One
15       One
75       Two
83       Two
53       One
25       One
6        One
106      Two
33       One
35       One
105      Two
139    Three
61       Two
49       One
110      Two
101      Two
1        One
81       Two
117      Two
48       One
38       One
86       Two
11       One
163    Three
42       One
96       Two
90       Two
31       One
20       One
175    Three
107      Two
148    Three
156    Three
145    Three
143    Three
127      Two
66       Two
36       One
126      Two
142    Three
59       Two
88       Two
170    Three
132    Three
151    Three
Name: Wine Type, dtype: object

In [37]:
from sklearn.metrics import classification_report, confusion_matrix
#confusion_matrix
#Es ideal para visualizar la distribución de los errores. 
#e permite detectar si tu modelo está confundiendo una clase específica con otra.

#classification_report
#Es un resumen estadístico que desglosa las métricas clave de evaluación para cada una de las clases de tu model

In [39]:
print(classification_report(y_test, predicciones))

              precision    recall  f1-score   support

         One       0.94      0.84      0.89        19
       Three       0.86      1.00      0.92        12
         Two       0.87      0.87      0.87        23

    accuracy                           0.89        54
   macro avg       0.89      0.90      0.89        54
weighted avg       0.89      0.89      0.89        54

In [40]:
print(confusion_matrix(y_test, predicciones))

[[16  0  3]
 [ 0 12  0]
 [ 1  2 20]]

In [1]:
#ejercicio

from sklearn.tree import DecisionTreeClassifier
import numpy as np

def entrenar_arbol_decision(X_train, y_train, X_test):
    modelo = DecisionTreeClassifier(random_state=42)
    modelo.fit(X_train, y_train)
    predicciones = modelo.predict(X_test)
    return predicciones