In [5]:
print("hello")

hello

In [11]:
import pandas as pd
df_nombreedad1 = pd.DataFrame(columns=['nombre', 'edad'])
df_nombreedad1

Empty DataFrame
Columns: [nombre, edad]
Index: []

In [23]:
import csv
import pandas as pd
# Existing DataFrame
df = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [25, 30]})
#otra forma de APPEND
df.loc[len(df.index)]=['luisalfredo', 45]
with open("/home/casa/nombres.csv") as file_obj:
    reader_obj=csv.DictReader(file_obj)
    print(reader_obj)
    for row in reader_obj:
        print(row)
        # Data to APPEND as a dictionary
        new_row = {'Name': row['nombre'], 'Age': row['edad']}
        # Append using concat
        df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
#imprimir DF
df

<csv.DictReader object at 0x7f7be02b8c10>
{'nombre': 'luis', 'edad': '0'}
{'nombre': 'pedro', 'edad': '0'}
{'nombre': 'maria', 'edad': '0'}

          Name Age
0        Alice  25
1          Bob  30
2  luisalfredo  45
3         luis   0
4        pedro   0
5        maria   0